title: Cs 50 Sandbox
description: data
template:
  repo: cs-50-sandbox-template
  name: cs-50-sandbox
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
